# Generated by Django 3.1.12 on 2022-01-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='post_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
