# Generated by Django 3.1.12 on 2022-01-06 04:05

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0002_auto_20220106_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(max_length=16, blank = True, null=True, verbose_name='lang'),
        ),
    ]