# Generated by Django 3.1.12 on 2022-01-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0003_auto_20220106_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
