# Generated by Django 3.1.12 on 2022-01-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0004_auto_20220106_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='post_count',
            field=models.IntegerField(default=0, verbose_name='posts'),
        ),
    ]
