# Generated by Django 3.1.12 on 2022-01-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0005_auto_20220106_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(blank=True, choices=[('🔰 Admin', '🔰 Admin'), ('🐳 Whale', '🐳 Whale'), ('🐋 Babywhale', '🐋 Babywhale'), ('🐬 Dolphin', '🐬 Dolphin'), ('❇️ Member', '❇️ Member'), ('🚫 Hustler', '🚫 Hustler')], max_length=15, null=True),
        ),
    ]
