# Generated by Django 3.1.12 on 2022-01-14 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0006_auto_20220111_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='language_code',
        ),
    ]
