# Generated by Django 3.1.14 on 2022-01-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0007_remove_telegramuser_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(max_length=2, null=True, verbose_name='lang'),
        ),
    ]
