# Generated by Django 3.1.14 on 2022-01-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0008_telegramuser_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='lang'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', '🔰 Admin'), ('Whale', '🐳 Whale'), ('Babywhale', '🐋 Babywhale'), ('Dolphin', '🐬 Dolphin'), ('Member', '❇️ Member'), ('Hustler', '🚫 Hustler')], max_length=15, null=True),
        ),
    ]
