# Generated by Django 3.1.14 on 2022-02-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0010_auto_20220225_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='has_status',
            field=models.BooleanField(default=False, verbose_name='Mb'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', '🔰 Admin'), ('Whale', '🐳 Whale'), ('Babywhale', '🐋 Babywhale'), ('Dolphin', '🐬 Dolphin'), ('Member', '❇️ Member'), ('Hustler', '🚫 Hustler'), ('Bot', '🔷 Bot')], max_length=15, null=True),
        ),
    ]
