# Generated by Django 3.1.14 on 2022-02-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0012_auto_20220227_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Lang'),
        ),
    ]
