# Generated by Django 3.1.14 on 2022-03-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0013_auto_20220227_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', '🔰 Admin'), ('Whale', '🐳 Whale'), ('Babywhale', '🐋 Babywhale'), ('Dolphin', '🐬 Dolphin'), ('Member', '🐡 Member'), ('Hustler', '🚫 Hustler'), ('Bot', '🔷 Bot')], max_length=15, null=True),
        ),
    ]
