# Generated by Django 3.1.14 on 2022-03-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0014_auto_20220302_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='language_code',
        ),
    ]
