# Generated by Django 4.0.6 on 2022-09-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0017_alter_telegramchat_id_alter_telegramstate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
