# Generated by Django 4.1.4 on 2022-12-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0019_telegramuser_warnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Lang'),
        ),
    ]
