# Generated by Django 4.1.4 on 2022-12-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0021_alter_telegramuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_bot',
        ),
    ]
