# Generated by Django 4.1.4 on 2023-02-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0022_remove_telegramuser_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='has_status',
            field=models.BooleanField(default=True, verbose_name='Mb'),
        ),
    ]
