# Generated by Django 4.1.7 on 2023-03-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altfishbot', '0023_telegramuser_is_bot_alter_telegramuser_has_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='premium'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='lang'),
        ),
    ]
