# Generated by Django 4.1.4 on 2022-12-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_referral_rename_bannedlist_bannedword'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_text', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['warning_text'],
            },
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.AlterModelOptions(
            name='bannedword',
            options={'ordering': ['banned_word']},
        ),
        migrations.AlterField(
            model_name='bannedword',
            name='banned_word',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='bannedword',
            name='warning_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderation.warningtext'),
        ),
    ]
