# Generated by Django 4.1.4 on 2022-12-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_warningtext_delete_referral_alter_bannedword_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warningtext',
            name='warning_number',
            field=models.IntegerField(default=3, verbose_name='Warnings max before banning user'),
        ),
    ]
