# Generated by Django 4.1.4 on 2022-12-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_warningtext_warning_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.TextField()),
            ],
        ),
    ]
