# Generated by Django 4.1.4 on 2022-12-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_rule_welcomemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active message'),
        ),
        migrations.AddField(
            model_name='welcomemessage',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active welcome'),
        ),
    ]
